from pydantic import BaseModel

class Description(BaseModel):
    username : str
    description : str
    date : str

db_descriptions = [
    Description(username="luciano", description="Desarrollador apasionado por la tecnología y el aprendizaje continuo", date="24/10"),
    Description(username="florencia", description="Estudiante de diseño gráfico con amor por el arte digital", date="24/10"),
    Description(username="franco", description="Entusiasta del gaming y la programación competitiva", date="25/10"),
    Description(username="test", description="Usuario de prueba para testing de la aplicación", date="25/10"),
    Description(username="santiago", description="Ingeniero civil especializado en construcciones sostenibles", date="26/10"),
    Description(username="maria", description="Profesora de matemáticas y tutora particular", date="26/10"),
    Description(username="diego", description="Fotógrafo freelance con experiencia en eventos", date="27/10"),
    Description(username="valentina", description="Estudiante de medicina y voluntaria en ONGs", date="27/10"),
    Description(username="mateo", description="Arquitecto con más de 10 años de experiencia", date="28/10"),
    Description(username="camila", description="Community manager y especialista en marketing digital", date="28/10"),
    Description(username="nicolas", description="Abogado corporativo enfocado en startups tecnológicas", date="29/10"),
    Description(username="sofia", description="Diseñadora de interiores y decoradora profesional", date="29/10"),
    Description(username="joaquin", description="Chef especializado en cocina mediterránea", date="30/10"),
    Description(username="isabella", description="Psicóloga clínica con enfoque en terapia cognitiva", date="30/10"),
    Description(username="tomas", description="Contador público y asesor financiero independiente", date="31/10"),
    Description(username="martina", description="Influencer de moda y creadora de contenido", date="31/10"),
    Description(username="benjamin", description="Músico profesional y productor musical", date="01/11"),
    Description(username="emma", description="Periodista deportiva y comentarista de fútbol", date="01/11"),
    Description(username="lucas", description="Personal trainer certificado y nutricionista", date="02/11"),
    Description(username="mia", description="Directora de recursos humanos en empresa multinacional", date="02/11"),
    Description(username="agustin", description="Veterinario especializado en animales exóticos", date="03/11"),
    Description(username="catalina", description="Economista y analista de mercados financieros", date="03/11"),
    Description(username="thiago", description="Desarrollador backend especializado en Python y FastAPI", date="04/11"),
    Description(username="julieta", description="Bailarina profesional y coreógrafa de danza contemporánea", date="04/11"),
    Description(username="emiliano", description="Gerente de proyectos con certificación PMP", date="05/11"),
    Description(username="antonella", description="Farmacéutica y especialista en dermocosmética", date="05/11"),
    Description(username="bautista", description="Piloto comercial y entusiasta de la aviación", date="06/11"),
    Description(username="renata", description="Sommelier profesional y consultora de vinos", date="06/11"),
    Description(username="lautaro", description="Electricista industrial con experiencia en automatización", date="07/11"),
    Description(username="victoria", description="Bióloga marina dedicada a la conservación de ecosistemas", date="07/11"),
    Description(username="facundo", description="Streamer de videojuegos y creador de contenido en Twitch", date="08/11"),
    Description(username="delfina", description="Traductora e intérprete de inglés y francés", date="08/11"),
    Description(username="santino", description="Odontólogo especializado en ortodoncia", date="09/11"),
    Description(username="francesca", description="Sommelier de café y barista profesional", date="09/11"),
    Description(username="lorenzo", description="Ingeniero mecánico y consultor industrial", date="10/11"),
    Description(username="olivia", description="Actriz de teatro y profesora de actuación", date="10/11"),
    Description(username="juancruz", description="Bombero voluntario y técnico en emergencias", date="11/11"),
    Description(username="alma", description="Escritora de novelas románticas y poeta", date="11/11"),
    Description(username="matias", description="Técnico en refrigeración y climatización", date="12/11"),
    Description(username="milagros", description="Enfermera especializada en cuidados intensivos", date="12/11"),
    Description(username="gael", description="DJ profesional y productor de música electrónica", date="13/11"),
    Description(username="pilar", description="Geóloga dedicada a la exploración de recursos minerales", date="13/11"),
    Description(username="ian", description="Mecánico automotriz especializado en vehículos híbridos", date="14/11"),
    Description(username="jazmin", description="Maestra de educación inicial y estimuladora temprana", date="14/11"),
    Description(username="felipe", description="Cirujano plástico con enfoque reconstructivo", date="15/11"),
    Description(username="clara", description="Ingeniera química y especialista en sustentabilidad", date="15/11"),
    Description(username="simon", description="Sociólogo e investigador social en temas urbanos", date="16/11"),
    Description(username="luna", description="Astrónoma aficionada y divulgadora científica", date="16/11"),
    Description(username="rodrigo", description="Carpintero artesanal y restaurador de muebles antiguos", date="17/11"),
    Description(username="abril", description="Relacionista pública y organizadora de eventos corporativos", date="17/11")
]
